baseurl = "http://vamp.io"
languageCode = "en-us"
title = "Vamp"
theme = "vamp-theme"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "magnetic.io"
	description = "Canary releasing and autoscaling for microservice systems"
	copyright = "Released under the Apache 2 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/magneticio/vamp"

	version = "0.9.5"
	logo = "images/logo.svg"
	favicon = "images/logo.svg"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "pink"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

[social]
	twitter = "magneticio"
	github  = "magneticio/vamp"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


# Top nav

[[menu.topnav]]
    name = "Product"
    identifier = "product"
    url = "/product/"
    weight = 10

[[menu.topnav]]
	name   = "Developers"
    identifier = "developers"
	url    = "/documentation/"
	weight = 30

[[menu.topnav]]
	name   = "Support"
	identifier = "support"
	url    = "/support/"
	weight = 40

# Main categories

[[menu.main]]
	name   = "Product"
	url    = "/product/why-use-vamp/"
	identifier = "product-top"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/how-vamp-works/architecture-and-components/"
	weight = 20

[[menu.main]]
	name   = "Support"
	url    = "/support/"
	weight = 30


[[menu.main]]
	name   = "About"
	url    = "/about/"
	weight = 40


# Side Menu Items, Parent should match the identifier of the main categories

[[menu.main]]
	name = "Use cases"
	url = "/product/use-cases"
	parent = "product-top"
	weight = 10

[[menu.main]]
	name  = "Vamp compared to..."
	url   = "/product/vamp-compared-to/proxies-and-load-balancers/"
	parent = "product-top"
	weight = 30

[[menu.main]]
	name	= "How Vamp works"
	url = "/documentation/how-vamp-works/architecture-and-components/"
	parent = "Documentation"
	weight = 10

[[menu.main]]
	name = "Install"
	identifier = "Installation"
	url = "/documentation/installation/overview"
	parent = "Documentation"
	weight = 20

[[menu.main]]
	name = "Tutorials"
	url = "/documentation/tutorials/overview"
	parent = "Documentation"
	weight = 30

[[menu.main]]
	name = "Using Vamp"
	url = "documentation/using-vamp/artifacts/"
	parent = "Documentation"
	weight = 40

[[menu.main]]
	name = "Configure"
	identifier = "Configuration"
	url = "/documentation/configure"
	parent = "Documentation"
	weight = 50

[[menu.main]]
	name = "Troubleshoot"
	identifier = "Troubleshooting"
	url = "/documentation/troubleshoot"
	parent = "Documentation"
	weight = 60

[[menu.main]]
	name = "API documentation"
	identifier = "API"
	url = "/documentation/api/api-reference"
	parent = "Documentation"
	weight = 70

[[menu.main]]
	name = "CLI documentation"
	identifier = "CLI"
	url = "/documentation/cli/cli-reference/"
	parent = "Documentation"
	weight = 80

[[menu.main]]
	name = "Release notes"
	url = "/documentation/release-notes/"
	parent = "Documentation"
	weight = 80
